import type { Venue } from '@/lib/planner/types'

// In-memory mirror of supabase/seed.sql. Lets the plan handler run end-to-end
// before the user stands up Supabase. Keep in sync — or stop using this once
// Supabase is wired up by unsetting the mock-mode fallback in /api/plan.

const id = (n: number) => `mock-${String(n).padStart(3, '0')}`

export const catalog: Venue[] = [
  {
    id: id(1),
    name: 'Umi Nagomi',
    lat: 1.2756,
    lng: 103.8443,
    address: '78 Tanjong Pagar Rd',
    cuisine_tags: ['japanese', 'omakase'],
    vibe_tags: ['cozy', 'celebratory'],
    dietary_flags: [],
    budget_band: 4,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800',
    chope_url: 'https://book.chope.co/booking?rid=umi-nagomi',
    hours_json: dailyDinner({ monClosed: true }),
    ph_hours_json: null,
    badge: 'critic_pick',
    badge_meta: { source: 'Michelin Guide 2025' },
    trending_score: 0.78,
    active: true,
  },
  {
    id: id(2),
    name: 'Candela',
    lat: 1.2802,
    lng: 103.8419,
    address: '49 Keong Saik Rd',
    cuisine_tags: ['spanish', 'tapas'],
    vibe_tags: ['adventurous', 'loud'],
    dietary_flags: [],
    budget_band: 3,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
    chope_url: 'https://book.chope.co/booking?rid=candela',
    hours_json: dailyDinner({ sunClosed: true, lateFri: true, lateSat: true }),
    ph_hours_json: null,
    badge: 'soft_launch',
    badge_meta: { opened: '2026-03-12' },
    trending_score: 0.85,
    active: true,
  },
  {
    id: id(3),
    name: 'The Pizza Stop',
    lat: 1.3112,
    lng: 103.7958,
    address: '27 Lorong Mambong, Holland Village',
    cuisine_tags: ['italian', 'pizza'],
    vibe_tags: ['cozy', 'low_key', 'outdoor'],
    dietary_flags: [],
    budget_band: 2,
    is_outdoor: true,
    photo_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    chope_url: 'https://book.chope.co/booking?rid=pizza-stop',
    hours_json: dailyDinner({ lunchWeekends: true }),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.35,
    active: true,
  },
  {
    id: id(4),
    name: 'Saffron & Clove',
    lat: 1.3068,
    lng: 103.8519,
    address: '48 Serangoon Rd',
    cuisine_tags: ['indian'],
    vibe_tags: ['low_key', 'cozy'],
    dietary_flags: ['vegetarian_friendly', 'vegan'],
    budget_band: 2,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800',
    chope_url: 'https://book.chope.co/booking?rid=saffron-clove',
    hours_json: dailyDinner({ lunchWeekends: true }),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.3,
    active: true,
  },
  {
    id: id(5),
    name: 'Wok Hei Bar',
    lat: 1.2854,
    lng: 103.8326,
    address: '78 Yong Siak St, Tiong Bahru',
    cuisine_tags: ['chinese', 'zi_char'],
    vibe_tags: ['adventurous', 'loud'],
    dietary_flags: [],
    budget_band: 2,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=800',
    chope_url: 'https://book.chope.co/booking?rid=wok-hei-bar',
    hours_json: dailyDinner({ lateFri: true, lateSat: true }),
    ph_hours_json: null,
    badge: 'award_fresh',
    badge_meta: { award: "World's 50 Best Discovery 2026" },
    trending_score: 0.72,
    active: true,
  },
  {
    id: id(6),
    name: 'Maison Papillon',
    lat: 1.3048,
    lng: 103.8318,
    address: '302 Orchard Rd',
    cuisine_tags: ['french'],
    vibe_tags: ['cozy', 'celebratory', 'romantic'],
    dietary_flags: [],
    budget_band: 3,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=800',
    chope_url: 'https://book.chope.co/booking?rid=maison-papillon',
    hours_json: dailyDinner({ sunClosed: true }),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.45,
    active: true,
  },
  {
    id: id(7),
    name: 'Kebab Junction',
    lat: 1.2996,
    lng: 103.8558,
    address: '14 Bali Lane, Bugis',
    cuisine_tags: ['middle_eastern', 'turkish'],
    vibe_tags: ['low_key', 'loud'],
    dietary_flags: ['halal', 'vegetarian_friendly'],
    budget_band: 2,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1625398407796-82650a8c9dd4?w=800',
    chope_url: 'https://book.chope.co/booking?rid=kebab-junction',
    hours_json: lunchAndDinner({ lateFri: true, lateSat: true }),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.28,
    active: true,
  },
  {
    id: id(8),
    name: 'Green Ember',
    lat: 1.3053,
    lng: 103.8089,
    address: 'Dempsey Hill',
    cuisine_tags: ['modern_european', 'vegetarian'],
    vibe_tags: ['cozy', 'romantic'],
    dietary_flags: ['vegetarian_friendly', 'vegan'],
    budget_band: 3,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
    chope_url: 'https://book.chope.co/booking?rid=green-ember',
    hours_json: dailyDinner({ monClosed: true, lunchWeekends: true }),
    ph_hours_json: null,
    badge: 'soft_launch',
    badge_meta: { opened: '2026-04-01' },
    trending_score: 0.7,
    active: true,
  },
  {
    id: id(9),
    name: 'Hanok',
    lat: 1.3064,
    lng: 103.8316,
    address: '181 Orchard Rd',
    cuisine_tags: ['korean', 'bbq'],
    vibe_tags: ['adventurous', 'celebratory', 'loud'],
    dietary_flags: [],
    budget_band: 3,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1632789395770-20e6f63be806?w=800',
    chope_url: 'https://book.chope.co/booking?rid=hanok',
    hours_json: dailyDinner({ lateFri: true, lunchWeekends: true }),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.52,
    active: true,
  },
  {
    id: id(11),
    name: 'Sunset Terrace',
    lat: 1.2789,
    lng: 103.8536,
    address: '1 Raffles Place Level 62',
    cuisine_tags: ['mediterranean'],
    vibe_tags: ['celebratory', 'outdoor', 'romantic'],
    dietary_flags: [],
    budget_band: 4,
    is_outdoor: true,
    photo_url: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800',
    chope_url: 'https://book.chope.co/booking?rid=sunset-terrace',
    hours_json: dailyDinner({ lateFri: true, lateSat: true }),
    ph_hours_json: null,
    badge: 'closing_soon',
    badge_meta: { ends_at: '2026-05-31', reason: 'rooftop pop-up final month' },
    trending_score: 0.88,
    active: true,
  },
  {
    id: id(12),
    name: 'Little Havana',
    lat: 1.2889,
    lng: 103.8472,
    address: '3A River Valley Rd, Clarke Quay',
    cuisine_tags: ['latin', 'cuban'],
    vibe_tags: ['adventurous', 'loud', 'outdoor'],
    dietary_flags: [],
    budget_band: 2,
    is_outdoor: true,
    photo_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800',
    chope_url: 'https://book.chope.co/booking?rid=little-havana',
    hours_json: dailyDinner({ lateFri: true, lateSat: true }),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.4,
    active: true,
  },
  {
    id: id(13),
    name: 'Yuzu Mezze',
    lat: 1.2913,
    lng: 103.8411,
    address: '30 Robertson Quay',
    cuisine_tags: ['japanese', 'mediterranean', 'fusion'],
    vibe_tags: ['adventurous', 'cozy'],
    dietary_flags: ['vegetarian_friendly'],
    budget_band: 3,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1514326640560-7d063ef2aed5?w=800',
    chope_url: 'https://book.chope.co/booking?rid=yuzu-mezze',
    hours_json: dailyDinner({ monClosed: true }),
    ph_hours_json: null,
    badge: 'soft_launch',
    badge_meta: { opened: '2026-02-20' },
    trending_score: 0.68,
    active: true,
  },
  {
    id: id(14),
    name: 'Dumpling Den',
    lat: 1.2831,
    lng: 103.8438,
    address: '18 Smith St, Chinatown',
    cuisine_tags: ['chinese', 'dim_sum', 'dumplings'],
    vibe_tags: ['low_key', 'loud'],
    dietary_flags: [],
    budget_band: 1,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800',
    chope_url: 'https://book.chope.co/booking?rid=dumpling-den',
    hours_json: allDay(),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.25,
    active: true,
  },
  {
    id: id(15),
    name: 'Ember & Oak',
    lat: 1.3059,
    lng: 103.8105,
    address: 'Block 11 Dempsey Rd',
    cuisine_tags: ['modern_european', 'grill'],
    vibe_tags: ['celebratory', 'outdoor', 'romantic'],
    dietary_flags: [],
    budget_band: 4,
    is_outdoor: true,
    photo_url: 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800',
    chope_url: 'https://book.chope.co/booking?rid=ember-oak',
    hours_json: dailyDinner({ monClosed: true }),
    ph_hours_json: null,
    badge: 'award_fresh',
    badge_meta: { award: "Asia's 50 Best 2026 — newcomer" },
    trending_score: 0.82,
    active: true,
  },
  {
    id: id(16),
    name: 'Noodle Alley',
    lat: 1.3107,
    lng: 103.7953,
    address: 'Holland Drive Food Centre',
    cuisine_tags: ['thai', 'street_food'],
    vibe_tags: ['low_key', 'loud'],
    dietary_flags: [],
    budget_band: 1,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800',
    chope_url: 'https://book.chope.co/booking?rid=noodle-alley',
    hours_json: lunchAndDinner({}),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.2,
    active: true,
  },

  // Real SG venues (placeholder data — curator should verify coords, hours, and Chope URLs)
  {
    id: id(17),
    name: 'Odette',
    lat: 1.2907,
    lng: 103.8519,
    address: '1 St Andrew’s Rd, National Gallery',
    cuisine_tags: ['french', 'modern_european'],
    vibe_tags: ['celebratory', 'romantic', 'cozy'],
    dietary_flags: [],
    budget_band: 4,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=800',
    chope_url: 'https://book.chope.co/booking?rid=odette',
    hours_json: dailyDinner({ sunClosed: true, monClosed: true }),
    ph_hours_json: null,
    badge: 'critic_pick',
    badge_meta: { source: 'Michelin 3-star' },
    trending_score: 0.6,
    active: true,
  },
  {
    id: id(18),
    name: 'Burnt Ends',
    lat: 1.3044,
    lng: 103.8099,
    address: '7 Dempsey Rd',
    cuisine_tags: ['modern_european', 'grill', 'australian'],
    vibe_tags: ['adventurous', 'celebratory', 'loud'],
    dietary_flags: [],
    budget_band: 4,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
    chope_url: 'https://book.chope.co/booking?rid=burnt-ends',
    hours_json: dailyDinner({ sunClosed: true, monClosed: true, lateFri: true, lateSat: true }),
    ph_hours_json: null,
    badge: 'award_fresh',
    badge_meta: { award: "Asia's 50 Best" },
    trending_score: 0.75,
    active: true,
  },
  {
    id: id(19),
    name: 'The Coconut Club',
    lat: 1.2815,
    lng: 103.8469,
    address: '28 Ann Siang Rd',
    cuisine_tags: ['malay', 'nasi_lemak', 'local'],
    vibe_tags: ['low_key', 'cozy'],
    dietary_flags: ['halal'],
    budget_band: 2,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=800',
    chope_url: 'https://book.chope.co/booking?rid=the-coconut-club',
    hours_json: lunchAndDinner({}),
    ph_hours_json: null,
    badge: 'critic_pick',
    badge_meta: { source: 'Straits Times' },
    trending_score: 0.5,
    active: true,
  },
  {
    id: id(20),
    name: 'Atlas Bar',
    lat: 1.3008,
    lng: 103.8601,
    address: '600 North Bridge Rd, Parkview Square',
    cuisine_tags: ['cocktail_bar', 'european'],
    vibe_tags: ['celebratory', 'romantic', 'cozy'],
    dietary_flags: [],
    budget_band: 4,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
    chope_url: 'https://book.chope.co/booking?rid=atlas-bar',
    hours_json: dailyDinner({ sunClosed: true, lateFri: true, lateSat: true }),
    ph_hours_json: null,
    badge: 'award_fresh',
    badge_meta: { award: "World's 50 Best Bars" },
    trending_score: 0.7,
    active: true,
  },
  {
    id: id(21),
    name: 'Labyrinth',
    lat: 1.2902,
    lng: 103.8571,
    address: '8 Raffles Ave, Esplanade Mall',
    cuisine_tags: ['modern_european', 'singaporean'],
    vibe_tags: ['adventurous', 'celebratory'],
    dietary_flags: [],
    budget_band: 4,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800',
    chope_url: 'https://book.chope.co/booking?rid=labyrinth',
    hours_json: dailyDinner({ sunClosed: true, monClosed: true }),
    ph_hours_json: null,
    badge: 'critic_pick',
    badge_meta: { source: 'Michelin' },
    trending_score: 0.62,
    active: true,
  },
  {
    id: id(22),
    name: 'Open Farm Community',
    lat: 1.3055,
    lng: 103.8071,
    address: '130E Minden Rd, Dempsey',
    cuisine_tags: ['modern_european', 'farm_to_table'],
    vibe_tags: ['outdoor', 'low_key', 'cozy'],
    dietary_flags: ['vegetarian_friendly'],
    budget_band: 3,
    is_outdoor: true,
    photo_url: 'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800',
    chope_url: 'https://book.chope.co/booking?rid=open-farm-community',
    hours_json: lunchAndDinner({ lunchWeekends: true }),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.42,
    active: true,
  },
  {
    id: id(23),
    name: 'Super Loco Robertson Quay',
    lat: 1.2916,
    lng: 103.8392,
    address: '60 Robertson Quay',
    cuisine_tags: ['mexican', 'latin'],
    vibe_tags: ['adventurous', 'loud', 'outdoor'],
    dietary_flags: ['vegetarian_friendly'],
    budget_band: 2,
    is_outdoor: true,
    photo_url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800',
    chope_url: 'https://book.chope.co/booking?rid=super-loco-robertson',
    hours_json: dailyDinner({ lateFri: true, lateSat: true, lunchWeekends: true }),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.38,
    active: true,
  },
  {
    id: id(24),
    name: 'Artichoke',
    lat: 1.2990,
    lng: 103.8560,
    address: '161 Middle Rd',
    cuisine_tags: ['middle_eastern', 'mediterranean'],
    vibe_tags: ['adventurous', 'cozy', 'low_key'],
    dietary_flags: ['vegetarian_friendly'],
    budget_band: 3,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1505935428862-770b6f24f629?w=800',
    chope_url: 'https://book.chope.co/booking?rid=artichoke',
    hours_json: dailyDinner({ monClosed: true, lateFri: true, lateSat: true }),
    ph_hours_json: null,
    badge: 'critic_pick',
    badge_meta: { source: 'Critics favourite' },
    trending_score: 0.48,
    active: true,
  },

  // Curation pass 2 (2026-04-24): coverage for vietnamese, american, cheap eats, east/west geography.
  {
    id: id(25),
    name: 'Nam Nam Noodle Bar',
    lat: 1.3046,
    lng: 103.8269,
    address: '501 Orchard Rd, Wheelock Place B2',
    cuisine_tags: ['vietnamese'],
    vibe_tags: ['low_key', 'cozy'],
    dietary_flags: [],
    budget_band: 1,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1580906853309-f5a1ecbcb81e?w=800',
    chope_url: 'https://book.chope.co/booking?rid=nam-nam-noodle-bar',
    hours_json: allDay(),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.22,
    active: true,
  },
  {
    id: id(26),
    name: 'Long Phung',
    lat: 1.3142,
    lng: 103.9023,
    address: '159 Joo Chiat Rd',
    cuisine_tags: ['vietnamese'],
    vibe_tags: ['low_key', 'loud'],
    dietary_flags: [],
    budget_band: 1,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1576577445504-6af96477db52?w=800',
    chope_url: 'https://book.chope.co/booking?rid=long-phung',
    hours_json: lunchAndDinner({}),
    ph_hours_json: null,
    badge: 'critic_pick',
    badge_meta: { source: 'Straits Times Food Picks' },
    trending_score: 0.33,
    active: true,
  },
  {
    id: id(27),
    name: 'Meatsmith Little India',
    lat: 1.3079,
    lng: 103.8540,
    address: '21 Campbell Lane',
    cuisine_tags: ['american', 'bbq'],
    vibe_tags: ['loud', 'adventurous'],
    dietary_flags: [],
    budget_band: 3,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
    chope_url: 'https://book.chope.co/booking?rid=meatsmith-little-india',
    hours_json: dailyDinner({ monClosed: true, lateFri: true, lateSat: true }),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.46,
    active: true,
  },
  {
    id: id(28),
    name: '25 Degrees Burger Bar',
    lat: 1.3005,
    lng: 103.8389,
    address: '320 Orchard Rd, Hotel G',
    cuisine_tags: ['american', 'burgers'],
    vibe_tags: ['low_key', 'loud'],
    dietary_flags: ['vegetarian_friendly'],
    budget_band: 2,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
    chope_url: 'https://book.chope.co/booking?rid=25-degrees-burger-bar',
    hours_json: allDay(),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.24,
    active: true,
  },
  {
    id: id(29),
    name: 'Hashida Singapore',
    lat: 1.2807,
    lng: 103.8465,
    address: '77 Amoy St',
    cuisine_tags: ['japanese', 'omakase'],
    vibe_tags: ['cozy', 'celebratory', 'romantic'],
    dietary_flags: [],
    budget_band: 4,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800',
    chope_url: 'https://book.chope.co/booking?rid=hashida-singapore',
    hours_json: dailyDinner({ sunClosed: true, monClosed: true }),
    ph_hours_json: null,
    badge: 'critic_pick',
    badge_meta: { source: 'Michelin 1-star' },
    trending_score: 0.66,
    active: true,
  },
  {
    id: id(30),
    name: 'Ristorante Pietrasanta',
    lat: 1.2935,
    lng: 103.7957,
    address: '5B Portsdown Rd',
    cuisine_tags: ['italian'],
    vibe_tags: ['romantic', 'cozy', 'outdoor'],
    dietary_flags: ['vegetarian_friendly'],
    budget_band: 3,
    is_outdoor: true,
    photo_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
    chope_url: 'https://book.chope.co/booking?rid=ristorante-pietrasanta',
    hours_json: lunchAndDinner({ lateFri: true, lateSat: true }),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.41,
    active: true,
  },
  {
    id: id(31),
    name: 'Fatto a Mano',
    lat: 1.2783,
    lng: 103.8411,
    address: '25 Bukit Pasoh Rd',
    cuisine_tags: ['italian', 'pizza'],
    vibe_tags: ['low_key', 'cozy'],
    dietary_flags: ['vegetarian_friendly'],
    budget_band: 2,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=800',
    chope_url: 'https://book.chope.co/booking?rid=fatto-a-mano',
    hours_json: dailyDinner({ sunClosed: true, monClosed: true }),
    ph_hours_json: null,
    badge: 'soft_launch',
    badge_meta: { opened: '2026-01-18' },
    trending_score: 0.58,
    active: true,
  },
  {
    id: id(32),
    name: 'Keng Eng Kee Seafood',
    lat: 1.2876,
    lng: 103.8036,
    address: 'Blk 124 Bukit Merah Lane 1',
    cuisine_tags: ['chinese', 'zi_char', 'seafood'],
    vibe_tags: ['loud', 'low_key'],
    dietary_flags: [],
    budget_band: 2,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=800',
    chope_url: 'https://book.chope.co/booking?rid=keng-eng-kee',
    hours_json: allDay(),
    ph_hours_json: null,
    badge: 'critic_pick',
    badge_meta: { source: 'Michelin Bib Gourmand' },
    trending_score: 0.44,
    active: true,
  },
  {
    id: id(33),
    name: 'Summer Pavilion',
    lat: 1.2897,
    lng: 103.8599,
    address: '7 Raffles Ave, Ritz-Carlton',
    cuisine_tags: ['chinese', 'dim_sum', 'cantonese'],
    vibe_tags: ['celebratory', 'cozy', 'romantic'],
    dietary_flags: [],
    budget_band: 4,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800',
    chope_url: 'https://book.chope.co/booking?rid=summer-pavilion',
    hours_json: lunchAndDinner({}),
    ph_hours_json: null,
    badge: 'critic_pick',
    badge_meta: { source: 'Michelin 1-star' },
    trending_score: 0.64,
    active: true,
  },
  {
    id: id(34),
    name: 'Violet Oon Singapore',
    lat: 1.3041,
    lng: 103.8325,
    address: '2 Orchard Turn, ION Orchard',
    cuisine_tags: ['peranakan', 'malay'],
    vibe_tags: ['celebratory', 'romantic', 'cozy'],
    dietary_flags: [],
    budget_band: 3,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1625938144755-652e08e359b7?w=800',
    chope_url: 'https://book.chope.co/booking?rid=violet-oon-ion',
    hours_json: lunchAndDinner({ lateFri: true, lateSat: true }),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.54,
    active: true,
  },
  {
    id: id(35),
    name: 'Tippling Club',
    lat: 1.2781,
    lng: 103.8436,
    address: '38 Tanjong Pagar Rd',
    cuisine_tags: ['modern_european', 'cocktail_bar'],
    vibe_tags: ['adventurous', 'celebratory'],
    dietary_flags: [],
    budget_band: 4,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
    chope_url: 'https://book.chope.co/booking?rid=tippling-club',
    hours_json: dailyDinner({ sunClosed: true, monClosed: true, lateFri: true, lateSat: true }),
    ph_hours_json: null,
    badge: 'award_fresh',
    badge_meta: { award: "Asia's 50 Best Bars" },
    trending_score: 0.71,
    active: true,
  },
  {
    id: id(36),
    name: 'Nouri',
    lat: 1.2810,
    lng: 103.8467,
    address: '72 Amoy St',
    cuisine_tags: ['modern_european', 'fusion'],
    vibe_tags: ['adventurous', 'cozy'],
    dietary_flags: ['vegetarian_friendly'],
    budget_band: 4,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
    chope_url: 'https://book.chope.co/booking?rid=nouri',
    hours_json: dailyDinner({ sunClosed: true, monClosed: true }),
    ph_hours_json: null,
    badge: 'critic_pick',
    badge_meta: { source: 'Michelin 1-star' },
    trending_score: 0.6,
    active: true,
  },
  {
    id: id(37),
    name: 'Cloudstreet',
    lat: 1.2807,
    lng: 103.8461,
    address: '84 Amoy St',
    cuisine_tags: ['modern_european'],
    vibe_tags: ['celebratory', 'romantic', 'adventurous'],
    dietary_flags: ['vegetarian_friendly'],
    budget_band: 4,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    chope_url: 'https://book.chope.co/booking?rid=cloudstreet',
    hours_json: dailyDinner({ sunClosed: true, monClosed: true }),
    ph_hours_json: null,
    badge: 'award_fresh',
    badge_meta: { award: "Asia's 50 Best 2026" },
    trending_score: 0.8,
    active: true,
  },
  {
    id: id(38),
    name: 'Long Beach Seafood @ East Coast',
    lat: 1.3042,
    lng: 103.9313,
    address: '1202 East Coast Parkway',
    cuisine_tags: ['chinese', 'seafood'],
    vibe_tags: ['loud', 'outdoor', 'low_key'],
    dietary_flags: [],
    budget_band: 3,
    is_outdoor: true,
    photo_url: 'https://images.unsplash.com/photo-1625944228741-72dbb97a21f1?w=800',
    chope_url: 'https://book.chope.co/booking?rid=long-beach-east-coast',
    hours_json: dailyDinner({ lunchWeekends: true }),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.39,
    active: true,
  },
  {
    id: id(39),
    name: 'PS. Cafe Dempsey',
    lat: 1.3036,
    lng: 103.8071,
    address: '28B Harding Rd',
    cuisine_tags: ['modern_european', 'brunch'],
    vibe_tags: ['outdoor', 'low_key', 'cozy', 'romantic'],
    dietary_flags: ['vegetarian_friendly'],
    budget_band: 3,
    is_outdoor: true,
    photo_url: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800',
    chope_url: 'https://book.chope.co/booking?rid=ps-cafe-dempsey',
    hours_json: {
      mon: [{ open: '0800', close: '2230' }],
      tue: [{ open: '0800', close: '2230' }],
      wed: [{ open: '0800', close: '2230' }],
      thu: [{ open: '0800', close: '2230' }],
      fri: [{ open: '0800', close: '2300' }],
      sat: [{ open: '0800', close: '2300' }],
      sun: [{ open: '0800', close: '2230' }],
    },
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.52,
    active: true,
  },
  {
    id: id(40),
    name: 'Tolido\u2019s Espresso Nook',
    lat: 1.3022,
    lng: 103.8487,
    address: '258 Selegie Rd',
    cuisine_tags: ['modern_european', 'brunch'],
    vibe_tags: ['low_key', 'cozy'],
    dietary_flags: ['vegetarian_friendly'],
    budget_band: 2,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=800',
    chope_url: 'https://book.chope.co/booking?rid=tolidos',
    hours_json: {
      mon: [{ open: '0830', close: '2130' }],
      tue: [{ open: '0830', close: '2130' }],
      wed: [{ open: '0830', close: '2130' }],
      thu: [{ open: '0830', close: '2130' }],
      fri: [{ open: '0830', close: '2200' }],
      sat: [{ open: '0830', close: '2200' }],
      sun: [{ open: '0830', close: '2130' }],
    },
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.27,
    active: true,
  },
  {
    id: id(41),
    name: 'Alma by Juan Amador',
    lat: 1.3046,
    lng: 103.8283,
    address: '22 Scotts Rd, Goodwood Park Hotel',
    cuisine_tags: ['mediterranean', 'modern_european', 'spanish'],
    vibe_tags: ['celebratory', 'romantic', 'cozy'],
    dietary_flags: ['vegetarian_friendly'],
    budget_band: 4,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800',
    chope_url: 'https://book.chope.co/booking?rid=alma',
    hours_json: dailyDinner({ sunClosed: true, monClosed: true, lunchWeekends: false }),
    ph_hours_json: null,
    badge: 'critic_pick',
    badge_meta: { source: 'Michelin 1-star' },
    trending_score: 0.58,
    active: true,
  },
  {
    id: id(42),
    name: '28 HongKong Street',
    lat: 1.2881,
    lng: 103.8466,
    address: '28 Hongkong St',
    cuisine_tags: ['cocktail_bar', 'american'],
    vibe_tags: ['cozy', 'adventurous', 'romantic'],
    dietary_flags: [],
    budget_band: 3,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800',
    chope_url: 'https://book.chope.co/booking?rid=28-hongkong-street',
    hours_json: {
      mon: [{ open: '1800', close: '0000' }],
      tue: [{ open: '1800', close: '0000' }],
      wed: [{ open: '1800', close: '0000' }],
      thu: [{ open: '1800', close: '0000' }],
      fri: [{ open: '1800', close: '0000' }],
      sat: [{ open: '1800', close: '0000' }],
      sun: [],
    },
    ph_hours_json: null,
    badge: 'award_fresh',
    badge_meta: { award: "World's 50 Best Bars" },
    trending_score: 0.69,
    active: true,
  },

  // Curation pass 3 (2026-04-24): non-eatery experiences and events. Uses the
  // existing schema with cuisine_tags overloaded for category (experience,
  // exhibition, nightlife, games, outdoor, art, music, nature). Chope URL left
  // null since these don't take restaurant reservations.
  {
    id: id(43),
    name: 'ArtScience Museum',
    lat: 1.2862,
    lng: 103.8598,
    address: '6 Bayfront Ave, Marina Bay Sands',
    cuisine_tags: ['experience', 'exhibition', 'art'],
    vibe_tags: ['adventurous', 'celebratory', 'cozy'],
    dietary_flags: [],
    budget_band: 2,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1566438480900-0609be27a4be?w=800',
    chope_url: 'https://www.marinabaysands.com/museum.html',
    hours_json: openDaily('1000', '1900'),
    ph_hours_json: null,
    badge: 'critic_pick',
    badge_meta: { source: 'Marina Bay icon — rotating headline exhibitions' },
    trending_score: 0.6,
    active: true,
  },
  {
    id: id(44),
    name: 'Van Gogh: The Immersive Experience',
    lat: 1.2540,
    lng: 103.8238,
    address: 'Resorts World Sentosa',
    cuisine_tags: ['experience', 'exhibition', 'art'],
    vibe_tags: ['adventurous', 'romantic', 'celebratory'],
    dietary_flags: [],
    budget_band: 3,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1574182245530-967d9b3831af?w=800',
    chope_url: 'https://www.rwsentosa.com/en/attractions',
    hours_json: openDaily('1000', '2100'),
    ph_hours_json: null,
    badge: 'closing_soon',
    badge_meta: { ends_at: '2026-06-30', reason: 'limited-run immersive pop-up' },
    trending_score: 0.88,
    active: true,
  },
  {
    id: id(45),
    name: 'Marvel: The Exhibition',
    lat: 1.2862,
    lng: 103.8598,
    address: 'ArtScience Museum, Marina Bay Sands',
    cuisine_tags: ['experience', 'exhibition'],
    vibe_tags: ['adventurous', 'loud', 'celebratory'],
    dietary_flags: [],
    budget_band: 2,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?w=800',
    chope_url: 'https://www.marinabaysands.com/museum/exhibitions.html',
    hours_json: openDaily('1000', '1900'),
    ph_hours_json: null,
    badge: 'closing_soon',
    badge_meta: { ends_at: '2026-05-15', reason: 'final weeks of travelling exhibit' },
    trending_score: 0.82,
    active: true,
  },
  {
    id: id(46),
    name: 'Gardens by the Bay — Flower Dome',
    lat: 1.2839,
    lng: 103.8636,
    address: '18 Marina Gardens Dr',
    cuisine_tags: ['experience', 'outdoor', 'nature'],
    vibe_tags: ['cozy', 'romantic', 'outdoor', 'low_key'],
    dietary_flags: [],
    budget_band: 2,
    is_outdoor: true,
    photo_url: 'https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=800',
    chope_url: 'https://www.gardensbythebay.com.sg/en/attractions/flower-dome.html',
    hours_json: openDaily('0900', '2100'),
    ph_hours_json: null,
    badge: 'soft_launch',
    badge_meta: { opened: '2026-03-01' },
    trending_score: 0.55,
    active: true,
  },
  {
    id: id(47),
    name: 'Cloud Forest Dome',
    lat: 1.2847,
    lng: 103.8648,
    address: '18 Marina Gardens Dr',
    cuisine_tags: ['experience', 'outdoor', 'nature'],
    vibe_tags: ['adventurous', 'romantic', 'outdoor'],
    dietary_flags: [],
    budget_band: 2,
    is_outdoor: true,
    photo_url: 'https://images.unsplash.com/photo-1600880292210-85937c7d9d9a?w=800',
    chope_url: 'https://www.gardensbythebay.com.sg/en/attractions/cloud-forest.html',
    hours_json: openDaily('0900', '2100'),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.45,
    active: true,
  },
  {
    id: id(48),
    name: 'National Gallery Singapore',
    lat: 1.2907,
    lng: 103.8519,
    address: '1 St Andrew\u2019s Rd',
    cuisine_tags: ['experience', 'exhibition', 'art'],
    vibe_tags: ['cozy', 'low_key', 'celebratory'],
    dietary_flags: [],
    budget_band: 2,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1545989253-02cc26577f88?w=800',
    chope_url: 'https://www.nationalgallery.sg/visit/tickets',
    hours_json: openDaily('1000', '1900'),
    ph_hours_json: null,
    badge: 'critic_pick',
    badge_meta: { source: 'Largest Southeast Asian art collection' },
    trending_score: 0.5,
    active: true,
  },
  {
    id: id(49),
    name: 'Singapore Art Museum @ Tanjong Pagar Distripark',
    lat: 1.2714,
    lng: 103.8219,
    address: '39 Keppel Rd, Tanjong Pagar Distripark',
    cuisine_tags: ['experience', 'exhibition', 'art'],
    vibe_tags: ['adventurous', 'cozy'],
    dietary_flags: [],
    budget_band: 2,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1536924430914-91f9e2041b83?w=800',
    chope_url: 'https://www.singaporeartmuseum.sg/visit/plan-your-visit',
    hours_json: openDaily('1000', '1900'),
    ph_hours_json: null,
    badge: 'soft_launch',
    badge_meta: { opened: '2026-02-14' },
    trending_score: 0.68,
    active: true,
  },
  {
    id: id(50),
    name: 'Timbre X S.E.A.',
    lat: 1.2714,
    lng: 103.8219,
    address: '39 Keppel Rd, The Winery',
    cuisine_tags: ['experience', 'music', 'nightlife'],
    vibe_tags: ['adventurous', 'loud', 'celebratory'],
    dietary_flags: [],
    budget_band: 3,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800',
    chope_url: 'https://timbregroup.asia/timbre-x-sea/',
    hours_json: {
      mon: [],
      tue: [],
      wed: [{ open: '1900', close: '0000' }],
      thu: [{ open: '1900', close: '0000' }],
      fri: [{ open: '1900', close: '0100' }],
      sat: [{ open: '1900', close: '0100' }],
      sun: [],
    },
    ph_hours_json: null,
    badge: 'award_fresh',
    badge_meta: { award: 'Best Live Music Venue 2026' },
    trending_score: 0.72,
    active: true,
  },
  {
    id: id(51),
    name: 'Blu Jaz Cafe',
    lat: 1.3018,
    lng: 103.8583,
    address: '11 Bali Lane',
    cuisine_tags: ['experience', 'music', 'nightlife'],
    vibe_tags: ['cozy', 'loud', 'low_key'],
    dietary_flags: [],
    budget_band: 2,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800',
    chope_url: 'https://www.blujaz.net/events',
    hours_json: {
      mon: [],
      tue: [{ open: '1800', close: '0000' }],
      wed: [{ open: '1800', close: '0000' }],
      thu: [{ open: '1800', close: '0100' }],
      fri: [{ open: '1800', close: '0200' }],
      sat: [{ open: '1800', close: '0200' }],
      sun: [{ open: '1800', close: '0000' }],
    },
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.38,
    active: true,
  },
  {
    id: id(52),
    name: 'Lockdown SG',
    lat: 1.2899,
    lng: 103.8460,
    address: '3A River Valley Rd, Clarke Quay',
    cuisine_tags: ['experience', 'games'],
    vibe_tags: ['adventurous', 'loud'],
    dietary_flags: [],
    budget_band: 2,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1581375383680-903f6686f31b?w=800',
    chope_url: 'https://lockdown.sg/',
    hours_json: openDaily('1200', '2330'),
    ph_hours_json: null,
    badge: 'critic_pick',
    badge_meta: { source: 'Top-rated escape rooms in SG' },
    trending_score: 0.42,
    active: true,
  },
  {
    id: id(53),
    name: 'Mind Cafe',
    lat: 1.3029,
    lng: 103.8381,
    address: '11A Prinsep St',
    cuisine_tags: ['experience', 'games'],
    vibe_tags: ['cozy', 'low_key', 'adventurous'],
    dietary_flags: ['vegetarian_friendly'],
    budget_band: 1,
    is_outdoor: false,
    photo_url: 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?w=800',
    chope_url: 'https://www.mindcafe.com.sg/',
    hours_json: openDaily('1200', '0000'),
    ph_hours_json: null,
    badge: 'none',
    badge_meta: null,
    trending_score: 0.3,
    active: true,
  },
  {
    id: id(54),
    name: 'Night Safari',
    lat: 1.4053,
    lng: 103.7890,
    address: '80 Mandai Lake Rd',
    cuisine_tags: ['experience', 'outdoor', 'nature'],
    vibe_tags: ['adventurous', 'outdoor', 'romantic'],
    dietary_flags: [],
    budget_band: 3,
    is_outdoor: true,
    photo_url: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=800',
    chope_url: 'https://www.mandai.com/en/night-safari.html',
    hours_json: {
      mon: [{ open: '1915', close: '0000' }],
      tue: [{ open: '1915', close: '0000' }],
      wed: [{ open: '1915', close: '0000' }],
      thu: [{ open: '1915', close: '0000' }],
      fri: [{ open: '1915', close: '0000' }],
      sat: [{ open: '1915', close: '0000' }],
      sun: [{ open: '1915', close: '0000' }],
    },
    ph_hours_json: null,
    badge: 'critic_pick',
    badge_meta: { source: 'World\u2019s first nocturnal wildlife park' },
    trending_score: 0.65,
    active: true,
  },
]

// -- hours templates -----------------------------------------------------

type HoursOpts = {
  monClosed?: boolean
  sunClosed?: boolean
  lateFri?: boolean
  lateSat?: boolean
  lunchWeekends?: boolean
}

function dailyDinner(opts: HoursOpts) {
  const hrs: Record<string, { open: string; close: string }[]> = {
    mon: opts.monClosed ? [] : [{ open: '1800', close: '2230' }],
    tue: [{ open: '1800', close: '2230' }],
    wed: [{ open: '1800', close: '2230' }],
    thu: [{ open: '1800', close: '2230' }],
    fri: [{ open: '1800', close: opts.lateFri ? '0000' : '2230' }],
    sat: opts.lunchWeekends
      ? [{ open: '1200', close: opts.lateSat ? '0000' : '2300' }]
      : [{ open: '1800', close: opts.lateSat ? '0000' : '2300' }],
    sun: opts.sunClosed
      ? []
      : opts.lunchWeekends
        ? [{ open: '1200', close: '2200' }]
        : [{ open: '1800', close: '2200' }],
  }
  return hrs
}

function lunchAndDinner(opts: HoursOpts) {
  return {
    mon: [{ open: '1100', close: '2200' }],
    tue: [{ open: '1100', close: '2200' }],
    wed: [{ open: '1100', close: '2200' }],
    thu: [{ open: '1100', close: '2200' }],
    fri: [{ open: '1100', close: opts.lateFri ? '0000' : '2230' }],
    sat: [{ open: '1100', close: opts.lateSat ? '0000' : '2230' }],
    sun: [{ open: '1100', close: '2200' }],
  }
}

function allDay() {
  return {
    mon: [{ open: '1100', close: '2200' }],
    tue: [{ open: '1100', close: '2200' }],
    wed: [{ open: '1100', close: '2200' }],
    thu: [{ open: '1100', close: '2200' }],
    fri: [{ open: '1100', close: '2230' }],
    sat: [{ open: '1100', close: '2230' }],
    sun: [{ open: '1100', close: '2200' }],
  }
}

// Single open/close window applied to every day. For experiences with no
// weekday variation (museums, parks).
function openDaily(open: string, close: string) {
  const w = [{ open, close }]
  return { mon: w, tue: w, wed: w, thu: w, fri: w, sat: w, sun: w }
}
